### ISSUE TITLE
not found handler

### ISSUE THREAD

**Issue by mybigman** [go-pkgz/routegroup#9]
can you add the ability to allow the use of my own not found handler and maybe why your at it method not allowed handler

**Comment by umputun** [comment]
>  and maybe why your at it method not allowed handler

Isn't this ability already in? https://github.com/go-pkgz/routegroup/blob/master/group.go#L109

Please note: the registration of the not-found handler may not be what you think it is. The only reason this library is doing it is to handle situations with middleware registration on an unset root handler. This is rather a trick, which I don't like that much, but in practice, it seems to works fine.

> can you add the ability to allow the use of my own not found handle

Well, this probably can be as easy as adding a function to assign a custom not-found handler, but I'm not sure if I like it. Let me think about it.

**Comment by mybigman** [comment]
> > and maybe why your at it method not allowed handler
> 
> Isn't this ability already in? https://github.com/go-pkgz/routegroup/blob/master/group.go#L109

Your right it does, I saw it as disabling the not found handler. The documentation could be improved here.

> > can you add the ability to allow the use of my own not found handle
> 
> Well, this probably can be as easy as adding a function to assign a custom not-found handler, but I'm not sure if I like it. Let me think about it.

It would be nice if you could. I use it for both rest API's and WEB.  

Not being able to return a custom 404 response with a custom page looks incomplete.

BTW Its a really nice package, I like especially that it uses the built-in server mux.

**Comment by umputun** [comment]
> Your right, it does. I saw it as disabling the not found handler. The documentation could be improved here.

https://github.com/go-pkgz/routegroup?tab=readme-ov-file#automatic-registration-of-notfoundhandler-as-catch-all-route

If you can think of  a better way to describe it, please submit a PR.

For custom 404, see #10. In addition to setting a custom response body, it can also set a custom status code. I recall some SPA frameworks expecting non-404 codes for not found resources for whatever reason. Not my area of expertise, but with this PR, the 404 handler can return any status code.

Please take a look and see if this is what you expected.

**Comment by mybigman** [comment]
> https://github.com/go-pkgz/routegroup?tab=readme-ov-file#automatic-registration-of-notfoundhandler-as-catch-all-route
> 
> If you can think of a better way to describe it, please submit a PR.

> For custom 404, see #10. In addition to setting a custom response body, it can also set a custom status code. I recall some SPA frameworks expecting non-404 codes for not found resources for whatever reason. Not my area of expertise, but with this PR, the 404 handler can return any status code.
> 
> Please take a look and see if this is what you expected.

Thanks for making the change, however its still not quite right.

Setting the `group.NotFoundHandler(func(w http.ResponseWriter, r *http.Request) {}` works as expected.

However sending a wrong verb to an endpoint results in a `404 response` instead of `Method Not Allowed`.

The if you disable the `group.DisableNotFoundHandler()` you get the proper response but this then disables the custom `NotFoundHandler`

It needs to handle the `Method Not Allowed` regardless of the `NotFoundHandler`. 

If you remove `group.DisableNotFoundHandler()` functionality and set it when setting the custom `NotFoundHandler` method it will be transparent to the user. 

This then would also help to simplify the readme regarding the `NotFoundHandler`.

With regards to the SPA, they sometimes return different statuses when resources aren't found so I wouldn't be to worried about that.

**Comment by umputun** [comment]
> If you remove group.DisableNotFoundHandler() functionality and set it when setting the custom NotFoundHandler method it will be transparent to the user.

Unfortunately, it is not as easy as it sounds. You're right that setting a not-found handler on the root is too aggressive and affects the built-in detection of "method not allowed." However, this issue existed before the change for the custom `NotFoundHandler`.

I can't simply remove the `b.register("/", notFoundHandler.ServeHTTP)` for two reasons:

-  I don't know of any other way to set a custom (or predefined) "not found" handler. As long as this "catch-all" route is set, it will also affect method mismatch detection. I haven't checked, but I believe we would see the same behavior using the stdlib mux directly.
-  Regardless of custom "not found" handling, we still need to have some "catch-all" route to handle middlewares on such "bad" routes.

If you have any bright ideas on how to address this issue without breaking the current functionality (by the way, removing `group.DisableNotFoundHandler` is a breaking change I want to avoid), please share.

**Comment by mybigman** [comment]
I think what needs to happen is you need to track the routes when they are registered just. Then you can compare the request vs whats registered.

Something like this.

```go
type route struct {
	method  string
	pattern string
	// handler http.Handler
}

// Bundle represents a group of routes with associated middleware.
type Bundle struct {
	mux            *http.ServeMux                    // the underlying mux to register the routes to
	basePath       string                            // base path for the group
	middlewares    []func(http.Handler) http.Handler // middlewares stack
	rootRegistered struct {
		once                       sync.Once // used to register a not found handler for the root path if no / route is registered
		set                        bool      // true if the root path is registered in the mux
		disableRootNotFoundHandler bool      // if true, the not found handler for the root path is not registered automatically
	}
	routes []route
}

// New creates a new Group.
func New(mux *http.ServeMux) *Bundle {
	b := &Bundle{
		mux:    mux,
		routes: []route{},
	}
	return b
}

func (b *Bundle) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	b.rootRegistered.once.Do(func() {
		if !b.rootRegistered.set && !b.rootRegistered.disableRootNotFoundHandler {
			// register a not found handler for the root path if no / route is registered
			// this is needed to be able to use middleware on all routes, for example logging
			notFoundHandler := http.NotFoundHandler()
			b.register("/", notFoundHandler.ServeHTTP)
		}
	})
	// -----------------------------------------------------------------------------
	// check if the route is registered
	// -----------------------------------------------------------------------------
	for _, route := range b.routes {
		if route.pattern == r.URL.Path {
			fmt.Printf("route: %s %s\n", route.method, route.pattern)
			fmt.Println("r.Method, r.URL.Path", r.Method, r.URL.Path)
			if route.method != r.Method {
				w.WriteHeader(http.StatusMethodNotAllowed)
				return
			}
		}
	}

	b.mux.ServeHTTP(w, r)
}
```

**Comment by umputun** [comment]
Adding the local registry of paths is something I'm trying to avoid here and keep it as bare-bones and close to the standard mux. In practice, the solution will be much more complex if we decide to go this way because the matching on the URL path won't work for patterns with dynamic parts, which are supported by the mux.

**Comment by mybigman** [comment]
Matching dynamic URLs paths is easy.

I close this as you seem set on not wanting to add features.

Appreciate the chat.

**Comment by umputun** [comment]
This is not about me not wanting to add the feature, but rather not wanting to introduce any routing-related handling outside of the mux. The issue is indeed in stdib; see https://github.com/golang/go/issues/65648.

It looks like a catch-all route is not a good strategy for a custom 404 in modern Go anymore.
